spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;
    username: sa
    password:
  sql:
    init:
      mode: always  # 스키마 자동 생성
      platform: r2dbc
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
management:
  health:
    db:
      enabled: false
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.r2dbc.core: debug
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui/swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /swagger-ui/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

llm:
  api:
    key: ${LLM_API_KEY}